# -*- coding: utf-8 -*-
"""KPMG Data Assessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JPu7996ulkyJzkR2D27d8QqaogOkF5fM
"""

import pandas as pd

"""# **1. Transactions Sheet Analysis**"""

Sheet1 = pd.read_excel("Raw_Data.xlsx", sheet_name='Transactions')

#Checking top rows for analysis
Sheet1.head()

#Getting Total Rows and Columns Information
Sheet1.shape

#Information about Data types used, Total columns filled etc.
Sheet1.info()

"""**Here Some fields columns are not filled completely and they are assumed to be blank. The blank rows or data needs to be cleaned before further analysis.**

Columns which contains blank, null data are:
1. online_order
2. brand
3. product_line
4. product_class
5. product_size
6. standard_cost
7. product_first_sold_date
"""

#How many values in each column are missing?
Sheet1.isnull().sum()

"""**The above analysis shows that there are so many values missing in the above particular columns**"""

#Searching for Duplicate Values in Transaction Sheet
Sheet1.duplicated().sum()

"""**The above analysis shows that there are no duplicate values in the Transaction sheet which is a good thing**"""

#Searching for uniqueness
Sheet1.nunique()

"""**The above analysis suggests that there are 20k transaction_id which are totally unique and hence we can say that each row or record can be uniquely identified using transaction_id**

# **2. Customer Demographic Sheet Analysis**
"""

Sheet2 = pd.read_excel("Raw_Data.xlsx", sheet_name='CustomerDemographic')

#Checking some rows to get more info
Sheet2.head()

#Total Rows and Columns Information
Sheet2.shape

"""**It seems like there are problems in the data related to the date of birth (DOB Column)**

The date format also contains string format data which may cause problem and it needs to be converted for further analysis
"""

#Information about Data types used, Total columns filled etc.
Sheet2.info()

#Total Empty cells or fields in this sheet
Sheet2.isnull().sum()

"""**From this analysis we get to know that there are some fields or cells which are blank**

These blank values can cause errors in calculations, the columns which contains blank values are:
1. last_name
2. DOB
3. job_title
4. job_industry_category
5. default
6. tenure
"""

#Finding Duplicate Values
Sheet2.duplicated().sum()

"""**There are no duplicated values found in this sheet of Customer Demographics**"""

#Searching for uniqueness
Sheet2.nunique()

"""**The above analysis shows that customer_id can be used as a unique key to identify the records**"""

#Checking the columns information (Seemed to contain various unknown values)
Sheet2['default'].value_counts()

#Checking the columns information (Seemed to contain various different values)
Sheet2['gender'].value_counts()

"""**The above two analysis shows that there are useless values in the default and gender field**

The default column contains various values which cannot be understood and doesn't seem to be related to any data and hence it can be dropped.

The gender column contains various types of representations which needs to be merged together for making the analysis easier Male - M, Female - F etc. Also there seems to be 'Femal' which is an error.
Either all values can be represented using (Male-Female-Unidentified) or (M-F-U)

# **3. New Customer List Sheet Analysis**
"""

Sheet3 = pd.read_excel("Raw_Data.xlsx", sheet_name='NewCustomerList')

#Checking few rows for general information
Sheet3.head()

#Total rows and columns in this sheet
Sheet3.shape

#Data type and total values filled information
Sheet3.info()

"""**This analysis shows us that there are few unnecessary columns**

Some unnecessary columns are 'Unnamed' from the range 16 to 20. These needs to be dropped for further analysis

We can also see that there are a few columns which contains empty or blank data
"""

#Dropping unnecessary columns for further analysis
NewSheet3 = Sheet3.drop(['Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19','Unnamed: 20'], axis=1)

#Checking Head for new sheet
NewSheet3.head()

#Checking for blank or empty values
NewSheet3.isnull().sum()

"""**The above analysis shows that there are few columns which are blank and these rows needs to be removed**

The columns which contains null values are:
1. last_name
2. DOB
3. job_title
4. job_industry_category
"""

#Checking Duplicate values
NewSheet3.duplicated().sum()

"""**There seems to be no duplicate records in this sheet as well**"""

#Checking Uniqueness
NewSheet3.nunique()

"""**According to the total number of rows in the sheet address seems to be the only unique key in this New Customers List**

Address doesn't seem fit for this role and it can be changed. Maybe a randomly generated string can be used to uniquely identify each record
"""

#Checking genders in New Customer List
NewSheet3['gender'].value_counts()

"""**This seems fine but replacing U with Unidentified will make the records look more sorted and easier to read**

# **4. Customer Address Sheet Analysis**
"""

Sheet4 = pd.read_excel("Raw_Data.xlsx", sheet_name='CustomerAddress')

#Reading top 5 rows
Sheet4.head()

#Getting total rows and columns
Sheet4.shape

#Understanding data types and filled columns
Sheet4.info()

#Checking for duplicate values
Sheet4.duplicated().sum()

#Checking consistency of Country
Sheet4['country'].value_counts()

#Checking consistency of States
Sheet4['state'].value_counts()

"""**From the above analysis it is safe to say that the Address table is the most consistent among others**

There are no duplicate or null values encountered in this table and is good to go.

The country and states also seems to be in order and any duplication in form of different name is not found.

# **CONCLUSION**

**The above data have been successfully analyzed and below are some findings**

Sheet 1: Transactions
1. Some values in particular columns seems to be blank
2. No duplicate values encountered
3. Transaction_id is unique and can be used to identify records.

Sheet 2: Customer Demographic
1. DOB column seems to contain strings which should be dates instead
2. Some cells are blank
3. No duplicate values encountered
4. A column named 'default' seems to contain unknown information which need to be dropped
5. Genders are represented using various methods eg(Male, M, Female, F) which needs to be changed to specific style

Sheet 3: New Customers List
1. There are a few unnecessary columns which are 'unnamed'
2. There seems to be empty cells in few columns
3. There is no duplication recorded
4. The U in gender can be replaced as Unidentified to make it match with Male-Female format

Sheet 4: Customer Address
1. No empty rows or cells
2. No duplications
3. All the data is unique and consistent/accurate
"""